# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install sqlite headers
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Install dependencies
      run: bundle install
      
    - name: Prepare Database
      run: bundle exec rails db:create db:migrate
      env:
        RAILS_ENV: test
        
    - name: setup-chromedriver
      # You may pin to the exact commit or the version.
      # uses: nanasess/setup-chromedriver@835cae695490330a7e390033b2b5bd67e6f8055e
      uses: nanasess/setup-chromedriver@v1.0.1
      
    - name: Run tests
      run: bundle exec rake
      
    - name: Create Coverage Artifact
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage/
